package com.alpajazel.bookrrow.databases;

import com.alpajazel.bookrrow.enums.BookStatus;
import com.alpajazel.bookrrow.enums.BookType;
import com.alpajazel.bookrrow.enums.Genre;
import com.alpajazel.bookrrow.enums.Language;
import com.alpajazel.bookrrow.models.Book;
import com.alpajazel.bookrrow.models.Consumer;
import com.alpajazel.bookrrow.models.Fiction;
import com.alpajazel.bookrrow.models.NonFiction;

import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.util.ArrayList;

/**
 * Class that connect to postgresql server.
 * Give query and get result which is related to book table in the schema
 *
 * @author M. Alwi Sukra
 * @version 1.0.0
 * @since 2019-05-10
 */
public class DatabaseBook extends DatabaseConnection {

    /**
     * Get a Consumer object by converting result to an object from query result
     *
     * @param consumerId the primary key that determine the customer row that the program want to take
     * @return Consumer object which have the consumer_id that have been specified
     * @throws SQLException when there is an error when executing jdbc method that interact with postgresql
     * @since 2019-05-10
     */
    private Consumer getConsumer(int consumerId) throws SQLException {
        Consumer consumer = null;

        int id = 0;
        String username = "", password = "", name = "", email = "", phoneNumber = "";

        PreparedStatement st = getConn().prepareStatement("SELECT * FROM consumer WHERE consumer_id = ?");
        st.setInt(1,consumerId);
        ResultSet rs = st.executeQuery();
        while (rs.next()){
            id = rs.getInt("consumer_id");
            username = rs.getString("username");
            password = rs.getString("password");
            name = rs.getString("name");
            email = rs.getString("email");
            phoneNumber = rs.getString("phone_number");
        }
        consumer = new Consumer(id,name,email,username,password,phoneNumber);
        st.close();
        rs.close();
        return consumer;
    }

    /**
     * Get a Book object from current ResultSet value (current position) from ResultSet object
     *
     * @param rs ResultSet Object that contains its current position value
     * @return Book object generated from a row that provided from the current rs
     * @throws SQLException when there is an error when executing jdbc method that interact with postgresql
     * @since 2019-05-10
     */
    private Book generateBookFromCurrentResult(ResultSet rs) throws SQLException {
        int id = rs.getInt("book_id");
        String title = rs.getString("title");
        String author = rs.getString("author");
        String description = rs.getString("description");
        Language language = Language.valueOf(rs.getString("language"));
        int year = rs.getInt("year");
        BookType bookType = BookType.valueOf(rs.getString("type"));
        BookStatus bookStatus = BookStatus.valueOf(rs.getString("book_status"));
        String genre = rs.getString("genre");
        Consumer consumer = getConsumer(id);
        Book book;
        if(bookType == BookType.FICTION){
            book = new Fiction(id, title, author, description, language, year, bookStatus, consumer, Genre.valueOf(genre));
        }else {
            book = new NonFiction(id, title, author, description, language, year, bookStatus, consumer);
        }
        return book;
    }

    /**
     * Get a Book object from current ResultSet value (current position) from ResultSet object
     *
     * @param rs ResultSet object that generated by executing a Statement
     * @return list of Book objects that generated by converting all rows in ResultSet given
     * @throws SQLException when there is an error when executing jdbc method that interact with postgresql
     * @since 2019-05-10
     */
    private ArrayList<Book> generateListFromResultGroup(ResultSet rs) throws SQLException {
        ArrayList<Book> books = new ArrayList<>();
        while (rs.next()){
            Book book = generateBookFromCurrentResult(rs);
            books.add(book);
        }
        return books;
    }

    /**
     * Get list of all Book objects in the book table in postgresql.
     * List of all Book objects are created by converting to an object for each row from the query result
     *
     * @return all Books from book table as an array list of Book object
     * @since 2019-05-10
     */
    public ArrayList<Book> getAllBooks() {
        try {
            PreparedStatement st = getConn().prepareStatement("SELECT * FROM book ORDER BY book_id");
            ResultSet rs = st.executeQuery();
            ArrayList<Book> books = generateListFromResultGroup(rs);
            st.close();
            rs.close();
            return books;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Get list of all Book objects in the book table in postgresql with available status.
     * List of all Book objects are created by converting to an object for each row from the query result
     *
     * @return all Books from book table with available status as an array list of Book object
     * @since 2019-05-10
     */
    public ArrayList<Book> getAllAvailableBooks() {
        try {
            PreparedStatement st = getConn().prepareStatement("SELECT * FROM book WHERE book_status = 'AVAILABLE' ORDER BY book_id ");
            ResultSet rs = st.executeQuery();
            ArrayList<Book> books = generateListFromResultGroup(rs);
            st.close();
            rs.close();
            return books;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }

    /**
     * Get list of all Book objects in the book table in postgresql with specific type.
     * List of Book objects are created by converting to an object for each row from the query result
     *
     * @param bookType will be specified in the SQL query to narrow down the result
     * @return all books from book table which have the specified type as an array
     * @since 2019-05-10
     */
    public ArrayList<Book> getAllBooksByType(BookType bookType) {
        try {
            PreparedStatement st = getConn().prepareStatement("SELECT * FROM book WHERE type = ? ORDER BY book_id");
            st.setString(1,bookType.getKeyName());
            ResultSet rs = st.executeQuery();
            ArrayList<Book> books = generateListFromResultGroup(rs);
            st.close();
            rs.close();
            return books;
        } catch (SQLException e) {
            e.printStackTrace();
            return null;
        }
    }
}
